## eigendecomposition exercise

In [1]:
# import numpy
import numpy as np
from numpy import linalg


**Task:** Create a matrix (2x2) called matrix 'A'.


In [2]:
A = np.array([[3,4],[5,6]])
A

array([[3, 4],
       [5, 6]])

In [3]:
A.shape

(2, 2)

In [4]:
B = np.array([3,4])
B

array([3, 4])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [5]:
def shape_2x2(matrix):
    """
    Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

    PARAMS:
        matrix (numpy.ndarray) - matrix to check
    RETURN:
        True (bool) - if matrix has shape 2x2
        False (bool) - if matrix has not shape 2x2

    """
    if matrix.shape == (2,2):
        return True
    else:
        return False

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [6]:
def determinant_2x2(matrix):
    """
    Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

    PARAMS:
        matrix (numpy.ndarray) - matrix to compute determinant
    RETURN:
        det (float) - matrix determinant
    """
    if shape_2x2(matrix) == True:
        determinant = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
        return determinant
    else:
        print("incorrect shape")
        

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [7]:
determinant_2x2(A)

-2

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [9]:
eigenvals, V = linalg.eig(A)

**Task:** Print the eigenvalues.

In [10]:
eigenvals

array([-0.21699057,  9.21699057])

**Task:** Print  the eigenvectors.

In [11]:
V

array([[-0.77925158, -0.54107946],
       [ 0.62671124, -0.84097147]])

**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [35]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

def eig_2x2(matrix):
    if shape_2x2(matrix):
        # Calculate tr(A)
        matrix_trace = matrix.trace()

        # Calculate inside the quadratic formula
        inside_sqrt = matrix_trace**2 - 4*determinant_2x2(matrix) + 0j

        # find eigen values
        eigenvalues = [((matrix_trace - np.sqrt(inside_sqrt))/2), 
                        ((matrix_trace + np.sqrt(inside_sqrt))/2)]

        # isolate the real values
        eigenvalues = np.sort(np.array([v.real if v.imag == 0 else v for v in eigenvalues]))

        eigen_vectors = []
        for eigv in eigenvalues:
            # turn the eigenvalue into a matrix, 
            # then see the difference between it and the original matrix
            matrix_minus_eig = matrix - (eigv*np.eye(matrix.shape[0]))
            # grab the vector
            eigen_vector = np.array([-matrix_minus_eig[0,1], matrix_minus_eig[0,0]])
            # flatten back down
            eigenvector_norm = eigen_vector/np.linalg.norm(eigen_vector)
            # add to list
            eigen_vectors.append(eigenvector_norm)
        eigen_vectors = np.array(eigen_vectors).T

    return eigenvalues, eigen_vectors
        

In [36]:
eig_2x2(A)

(array([-0.21699057,  9.21699057]),
 array([[-0.77925158, -0.54107946],
        [ 0.62671124, -0.84097147]]))

In [34]:
eigenvals, V = linalg.eig(A)

In [17]:
eigenvals

array([-0.21699057,  9.21699057])

In [25]:
matrix_trace = A.trace()
matrix_trace

9

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [37]:

eig_2x2(A)

(array([-0.21699057,  9.21699057]),
 array([[-0.77925158, -0.54107946],
        [ 0.62671124, -0.84097147]]))

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [42]:
myvals, myvectors = eig_2x2(A)
npvals, npvectors = linalg.eig(A)

print(np.allclose(myvals, npvals))
print(np.allclose(myvectors, npvectors))

True
True


**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [44]:
B = np.array([[0,1],[-1,0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [45]:
b_myvals, b_myvectors = eig_2x2(B)
b_npvals, b_npvectors = linalg.eig(B)

**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [46]:
print(np.allclose(b_myvals, b_npvals))
print(np.allclose(b_myvectors, b_npvectors))

False
False


**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?

In [47]:
b_myvals

array([0.-1.j, 0.+1.j])

In [48]:
b_npvals

array([0.+1.j, 0.-1.j])

In [49]:
b_myvectors

array([[-0.70710678+0.j        , -0.70710678+0.j        ],
       [ 0.        +0.70710678j,  0.        -0.70710678j]])

In [50]:
b_npvectors

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        +0.70710678j, 0.        -0.70710678j]])