## Matrix Decomposition Exercise

In [2]:
# import numpy
import numpy as np

**Task:** Generate a random matrix 'A' with a shape of 150x50, using the '**np.random.rand**' function.

In [3]:
A = np.random.rand(150,50)
A

array([[0.76714971, 0.02429214, 0.50914031, ..., 0.83990669, 0.29037642,
        0.4801526 ],
       [0.75163114, 0.07979055, 0.07186639, ..., 0.28042152, 0.78429178,
        0.04053146],
       [0.5116284 , 0.97635115, 0.03618338, ..., 0.22840083, 0.18395814,
        0.34690315],
       ...,
       [0.57419071, 0.70515146, 0.31631057, ..., 0.72354613, 0.50803435,
        0.73442185],
       [0.00588928, 0.77978757, 0.27741789, ..., 0.68617854, 0.41524485,
        0.68240458],
       [0.67731895, 0.71497232, 0.16089827, ..., 0.96811515, 0.17003277,
        0.49405809]])

**Task:** Check the shape of 'A'.

In [4]:
A.shape

(150, 50)

**Task:** Decompose matrix 'A' with SVD using numpy (decompose into matrices U,D,V).

In [19]:
U, D, V = np.linalg.svd(A, full_matrices=False)

In [20]:
np.diag(D).shape

(50, 50)

**Task:** Check the shapes of matrices U,D,V.

In [21]:
print(U.shape)
print(D.shape)
print(V.shape)

(150, 50)
(50,)
(50, 50)


**Task:** Reconstruct matrix 'A' from matrices U,D,V.

In [22]:
A_rec = U @ np.diag(D) @ V
A_rec

array([[0.76714971, 0.02429214, 0.50914031, ..., 0.83990669, 0.29037642,
        0.4801526 ],
       [0.75163114, 0.07979055, 0.07186639, ..., 0.28042152, 0.78429178,
        0.04053146],
       [0.5116284 , 0.97635115, 0.03618338, ..., 0.22840083, 0.18395814,
        0.34690315],
       ...,
       [0.57419071, 0.70515146, 0.31631057, ..., 0.72354613, 0.50803435,
        0.73442185],
       [0.00588928, 0.77978757, 0.27741789, ..., 0.68617854, 0.41524485,
        0.68240458],
       [0.67731895, 0.71497232, 0.16089827, ..., 0.96811515, 0.17003277,
        0.49405809]])

**Task:** Compare matrices 'A' and 'A_rec' with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [23]:
np.allclose(A, A_rec)

True

In [24]:
A.shape

(150, 50)

**Task:** Reduce the dimnesion of matrix 'A' to shape 150x20 with SVD (try both equations).

In [11]:
reducedA = U[:,:20].dot(np.diag(D[:20])) 


In [12]:
reducedA_alt = V[:,:20].dot(np.diag(D[:20]))

**Task:** Print the shape.

In [13]:
reducedA.shape

(150, 20)

**Task:** Compare the two results with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [14]:
np.allclose(A,reducedA)

ValueError: operands could not be broadcast together with shapes (150,50) (150,20) 

**Task:** Filter the noise from matrix 'A' with 20 largest singular vectors (keep the shape of (150x50)).

In [27]:
reconstA = np.matrix(U[:,:20]) * np.diag(D[:20]) * np.matrix(U[:20,:])


(150, 50)

**Task:** Check the shape.

In [28]:
reconstA.shape

(150, 50)

**Task:** Define the function `'SVD'` which perform singular values decomposition.

Do not forget to hceck the shape of the input matrix.

In [29]:
A = np.random.rand(150,50)
A

array([[0.56446669, 0.2928134 , 0.66413159, ..., 0.77964142, 0.15214593,
        0.78301921],
       [0.57045498, 0.74296635, 0.03315863, ..., 0.82823686, 0.70991532,
        0.35782611],
       [0.76276593, 0.45441651, 0.71921361, ..., 0.78117862, 0.28573521,
        0.02907876],
       ...,
       [0.89491745, 0.46010353, 0.14094523, ..., 0.44109569, 0.97646862,
        0.75633947],
       [0.75496958, 0.79506467, 0.51259196, ..., 0.03046799, 0.37470131,
        0.91908522],
       [0.08202616, 0.91381443, 0.82819117, ..., 0.19832638, 0.53073826,
        0.84447061]])

In [47]:
W = np.dot(A,np.transpose(A))
W_val, W_vec = np.linalg.eig(W)
U = W_vec

Z = np.dot(np.transpose(A), A)
Z_val, Z_vec = np.linalg.eig(Z)
V = Z_vec



array([[-0.13970257, -0.14570745, -0.13775187, ..., -0.14893878,
        -0.15162933, -0.14025675],
       [ 0.11929596, -0.01563602, -0.25013073, ...,  0.05134046,
        -0.14543526,  0.07553529],
       [-0.03693073, -0.08538789,  0.17921549, ...,  0.03924657,
        -0.06897389,  0.03411973],
       ...,
       [ 0.19825316,  0.02243067, -0.0217143 , ...,  0.03199794,
         0.04816783, -0.37548031],
       [-0.33671649,  0.13390044, -0.07887452, ...,  0.14265816,
         0.14980996,  0.08216593],
       [ 0.00476253,  0.06367199, -0.21216678, ...,  0.2156742 ,
        -0.06822945,  0.34874892]])

In [ ]:
"""
PARAMS:
    A (numpy.ndarray) - matrix to decompose
RETURN:a
    U (numpy.ndarray) - left singular vectors
    SV (numpy.ndarray) - singular values
    V (numpy.ndarray) - right singular vectors
"""

**Task:** Call the function `'SVD'` on matrix 'A'.