### Logistic Regression Exercise

In [21]:
# import numpy
import numpy as np

# import linear_model and datasets from sklearn
from sklearn import linear_model, datasets
from sklearn.linear_model import LogisticRegression

# import GridSearchCV from sklearn
from sklearn.model_selection import GridSearchCV

import pandas as pd

import plotly.graph_objects as go
import plotly.express as px
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, roc_auc_score, plot_roc_curve

In [2]:
# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target

* print the shape of X

In [3]:
X.shape

(150, 4)

* print y

In [4]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


* create a logistic regression model
    - **Note:** Spend some time on the logistic regression documentation to get familiar with the available parameters.

In [5]:

logreg = LogisticRegression()

* create a regularization space for the **'penalty'** parameter (a.k.a. what values do we want to insert into our GridSearch?)

In [6]:
param_candidates = [
    {'C':list(np.arange(0.2,10,0.2)), 'penalty': ['l2'], 'solver': ['newton-cg','lbfgs','sag']},
    {'C':list(np.arange(0.2,10,0.2)), 'penalty': ['l1','l2'], 'solver': ['liblinear']}
]

gridclf = GridSearchCV(estimator=logreg, param_grid=param_candidates, n_jobs=-1)
gridclf.fit(X,y)


/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the 

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [0.2, 0.4, 0.6000000000000001, 0.8, 1.0, 1.2,
                                1.4000000000000001, 1.6, 1.8, 2.0, 2.2,
                                2.4000000000000004, 2.6000000000000005,
                                2.8000000000000003, 3.0000000000000004, 3.2,
                                3.4000000000000004, 3.6000000000000005,
                                3.8000000000000003, 4.0, 4.2, 4.4,
                                4.6000000000000005, 4.800000000000001,
                                5.000000000000001,...
                                1.4000000000000001, 1.6, 1.8, 2.0, 2.2,
                                2.4000000000000004, 2.6000000000000005,
                                2.8000000000000003, 3.0000000000000004, 3.2,
                                3.4000000000000004, 3.6000000000000005,
                                3.8000000000000003, 4.0, 4.2, 4.4,
                                4.6000000000000005, 4.800000000000001,
                                5.000000000000001, 5.2, 5.4, 5.6000000000000005,
                                5.800000000000001, 6.000000000000001, ...],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']}])

In [7]:
gridclf.best_params_

{'C': 0.4, 'penalty': 'l2', 'solver': 'sag'}

* create a regularization space for the **'c'** parameter (a.k.a. what values do we want to insert into our GridSearch?)

* create a hyperparameter options dictionary

* create a grid search using 5-fold cross validation

* fit the grid search

* take the best model from grid search

* print the best hyperparameters

In [8]:
gridclf.best_params_

{'C': 0.4, 'penalty': 'l2', 'solver': 'sag'}

* predict the target vector
    - class ( *predict* )
    - probabilities ( *predict_proba* )

In [9]:
model = LogisticRegression(C=0.4, penalty='l2', solver='sag', random_state=123, max_iter=100) # gridclf.best_params_ <-check for the dictionnary
model.fit(X,y)

/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(C=0.4, random_state=123, solver='sag')

In [10]:
y_predictions = model.predict(X)
y_predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
y_scores = model.predict_proba(X)
y_scores

array([[9.64071066e-01, 3.59200306e-02, 8.90319622e-06],
       [9.24896856e-01, 7.50773196e-02, 2.58240835e-05],
       [9.51573843e-01, 4.84109193e-02, 1.52380783e-05],
       [9.20643818e-01, 7.93166425e-02, 3.95395064e-05],
       [9.68687036e-01, 3.13048672e-02, 8.09708582e-06],
       [9.65617027e-01, 3.43681646e-02, 1.48080523e-05],
       [9.55558584e-01, 4.44209169e-02, 2.04994179e-05],
       [9.50045889e-01, 4.99376381e-02, 1.64730019e-05],
       [9.09761660e-01, 9.01910832e-02, 4.72571902e-05],
       [9.24245597e-01, 7.57299051e-02, 2.44979545e-05],
       [9.68920288e-01, 3.10729294e-02, 6.78273392e-06],
       [9.39541836e-01, 6.04304786e-02, 2.76849612e-05],
       [9.25713129e-01, 7.42642930e-02, 2.25781771e-05],
       [9.53582680e-01, 4.64050003e-02, 1.23193115e-05],
       [9.88813143e-01, 1.11858985e-02, 9.58821242e-07],
       [9.88892952e-01, 1.11047946e-02, 2.25375568e-06],
       [9.83142358e-01, 1.68540202e-02, 3.62132021e-06],
       [9.63321425e-01, 3.66674

In [17]:
model.score(X,y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
model.classes_

array([0, 1, 2])

In [25]:
y.shape

(150,)

In [32]:
y_onehot

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

[150 rows x 3 columns]

In [33]:
y_onehot.iloc[:, i]

0      0
1      0
2      0
3      0
4      0
      ..
145    1
146    1
147    1
148    1
149    1
Name: 2, Length: 150, dtype: uint8

In [36]:
# Use scikit learn plotting instead!!!

# import scikitplot as skplt 
# import matplotlib.pyplot as plt  
# skplt.metrics.plot_roc_curve(y_true, y_probas) 
# plt.show()

- plot the ROC curve and print the AUC

In [31]:
# encode classes
y_onehot = pd.get_dummies(y, columns=model.classes_)

# Create an empty figure, and iteratively add new lines
# every time we compute a new class
fig = go.Figure()
fig.add_shape(
    type='line', line=dict(dash='dash'),
    x0=0, x1=1, y0=0, y1=1
)

for i in range(y_scores.shape[1]):
    y_true = y_onehot.iloc[:, i]
    y_score = y_scores[:, i]

    fpr, tpr, _ = roc_curve(y_true, y_score)
    auc_score = roc_auc_score(y_true, y_score)

    name = f"{y_onehot.columns[i]} (AUC={auc_score:.2f})"
    fig.add_trace(go.Scatter(x=fpr, y=tpr, name=name, mode='lines'))

fig.update_layout(
    xaxis_title='False Positive Rate',
    yaxis_title='True Positive Rate',
    yaxis=dict(scaleanchor="x", scaleratio=1),
    xaxis=dict(constrain='domain'),
    width=700, height=500
)


* print the Logreg coeficients

In [ ]:
model.coef_

array([[ 0.3215154 ,  1.12811796, -1.79737264, -0.81143635],
       [ 0.22549282, -0.39088542,  0.0289476 , -0.59770958],
       [-0.54700822, -0.73723254,  1.76842505,  1.40914594]])

* print the Logreg intercepts

In [ ]:
model.intercept_

array([ 2.05126086,  1.96802422, -4.01928508])