## Logistic Regression Challenge

In [115]:
#import the required packages here
import pandas as pd
import numpy as np
import re

from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

import statsmodels.api as sm
import statsmodels.formula.api as smf

import seaborn as sns


### Task 1: Download the data and load them into Python.
You can find the data [**here**](https://drive.google.com/file/d/0Bz9_0VdXvv9bX0MzUEhVdmpCc3c/view?usp=sharing&resourcekey=0-BirYbvtYO-hSEt09wpEBRw).

**Note**
- Features and response variables are in different files.
- Be careful about number of spaces between the values in the file.

In [82]:
# get headers
headers = pd.read_csv("data/Smartphone_Sensor_Data/features.txt", header=None, engine='python', sep=r'[ ]{1,}')
columns = list(headers[1])

In [143]:
# get feature data
features = pd.read_csv("data/Smartphone_Sensor_Data/train/X_train.txt", header=None, engine='python', sep=r'[ ]{1,}')

# assign column names

features.columns = columns

In [152]:
# find column names that include mean values
columns = np.array(columns)
columns_mean = columns[np.where(np.char.find(columns, 'mean()') >= 0)]
columns_meanx = columns[np.where(np.char.find(columns, 'mean()-X') >= 0)]

In [86]:
# filter for only mean values
features

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245         -0.975300         -0.960322         -0.998807   
2            -0.995380         -0.967187         -0.978944         -0.996520   
3            -0.996091         -0.983403         -0.990675         -0.997099   
4            -0.998139         -0.980817         -0.990482         -0.998321   
...                ...               ...               ...               ...   
7347         -0.195387          0.039905          0.077078         -0.282301   
7348         -0.235309          0.004816          0.059280         -0.322552   
7349         -0.218218         -0.103822          0.274533         -0.304515   
7350         -0.219139         -0.111412          0.268893         -0.310487   
7351         -0.269270         -0.087212          0.177404         -0.377404   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...   
1            -0.974914         -0.957686         -0.943068  ...   
2            -0.963668         -0.977469         -0.938692  ...   
3            -0.982750         -0.989302         -0.938692  ...   
4            -0.979672         -0.990441         -0.942469  ...   
...                ...               ...               ...  ...   
7347          0.043616          0.060410          0.210795  ...   
7348         -0.029456          0.080585          0.117440  ...   
7349         -0.098913          0.332584          0.043999  ...   
7350         -0.068200          0.319473          0.101702  ...   
7351         -0.038678          0.229430          0.269013  ...   

      fBodyBodyGyroJerkMag-meanFreq()  fBodyBodyGyroJerkMag-skewness()  \
0                           -0.074323                        -0.298676   
1                            0.158075                        -0.595051   
2                            0.414503                        -0.390748   
3                            0.404573                        -0.117290   
4                            0.087753                        -0.351471   
...                               ...                              ...   
7347                        -0.070157                        -0.588433   
7348                         0.165259                        -0.390738   
7349                         0.195034                         0.025145   
7350                         0.013865                         0.063907   
7351                        -0.058402                        -0.387052   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                           -0.710304                    -0.112754   
1                           -0.861499                     0.053477   
2                           -0.760104                    -0.118559   
3                           -0.482845                    -0.036788   
4                           -0.699205                     0.123320   
...                               ...                          ...   
7347                        -0.880324                    -0.190437   
7348      

In [145]:
target = pd.read_csv("data/Smartphone_Sensor_Data/train/y_train.txt", header=None)
target = target[0]
target

0       5
1       5
2       5
3       5
4       5
       ..
7347    2
7348    2
7349    2
7350    2
7351    2
Name: 0, Length: 7352, dtype: int64

### Task 2: Create a binary target variable: categories 1,2,3 --> 1, categories 4,5,6 --> 0 
This will represent a binary variable indicating if person is walking or not.

In [101]:
binarytarget = target
binarytarget = binarytarget.replace(to_replace={2:1,3:1,4:0,5:0,6:0})

### Task 3

+ Create a Univariate Binary Logistic Regression with feature number 54, which represents `tGravityAcc-min()-Y`: gravity acceleration signals in direction of Y.
+ Compare the results of the Logistic regressions from different Python packages (sklearn, statsmodel).
+ Plot the **fit** of predicted probabilities to the original values.

In [102]:
# get the independant variable
feature = features['tGravityAcc-min()-Y']
feature

0      -0.123213
1      -0.114893
2      -0.114893
3      -0.121336
4      -0.121834
          ...   
7347   -0.234998
7348   -0.234998
7349   -0.216004
7350   -0.210542
7351   -0.212149
Name: tGravityAcc-min()-Y, Length: 7352, dtype: float64

In [103]:
# reshape array
feature = np.array(feature).reshape(-1,1)

# fit model
binarymodel = LogisticRegression().fit(feature, binarytarget)

array([1, 1, 1, ..., 1, 1, 1])

In [111]:
# make a prediction
binary_pred = binarymodel.predict(feature)
np.unique(binary_pred, return_counts=True)

(array([0, 1]), array([3449, 3903]))

In [114]:
# plot the confusion matrix
cnf_matrix = metrics.confusion_matrix(binarytarget, binary_pred)
cnf_matrix

array([[2889, 1178],
       [ 560, 2725]])

In [150]:
# build the model

log_reg = sm.Logit(binarytarget, feature).fit()
print(log_reg.summary())

Optimization terminated successfully.
         Current function value: 0.494212
         Iterations 7
                           Logit Regression Results                           
Dep. Variable:                      0   No. Observations:                 7352
Model:                          Logit   Df Residuals:                     7351
Method:                           MLE   Df Model:                            0
Date:                Tue, 28 Jun 2022   Pseudo R-squ.:                  0.2811
Time:                        21:15:15   Log-Likelihood:                -3633.4
converged:                       True   LL-Null:                       -5054.4
Covariance Type:            nonrobust   LLR p-value:                       nan
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -5.1002      0.129    -39.642      0.000      -5.352      -4.848


### Task 4
- Try to fit a Binary Logistic Regression with all the features? How many are significant?

In [138]:
binarytarget

dtype('int64')

In [156]:
features_mean = features[columns_mean]
features_meanx

tBodyAcc-mean()-X  tGravityAcc-mean()-X  tBodyAccJerk-mean()-X  \
0              0.288585              0.963396               0.077996   
1              0.278419              0.966561               0.074007   
2              0.279653              0.966878               0.073636   
3              0.279174              0.967615               0.077321   
4              0.276629              0.968224               0.073444   
...                 ...                   ...                    ...   
7347           0.299665              0.923148              -0.319227   
7348           0.273853              0.918343              -0.422605   
7349           0.273387              0.919810               0.096541   
7350           0.289654              0.922323              -0.025849   
7351           0.351503              0.918707               0.075052   

      tBodyGyro-mean()-X  tBodyGyroJerk-mean()-X  fBodyAcc-mean()-X  \
0              -0.006101               -0.099167          -0.994783   
1              -0.016112               -0.110503          -0.997451   
2              -0.031698               -0.108486          -0.993594   
3              -0.043410               -0.091170          -0.995491   
4              -0.033960               -0.090770          -0.997286   
...                  ...                     ...                ...   
7347           -0.035024                0.040906          -0.131366   
7348            0.118696               -0.144067          -0.159077   
7349           -0.213192               -0.231529          -0.345767   
7350           -0.406205               -0.079919          -0.400368   
7351           -0.041810                0.263048          -0.265262   

      fBodyAccJerk-mean()-X  fBodyGyro-mean()-X  
0                 -0.992332           -0.986574  
1                 -0.995032           -0.977387  
2                 -0.990994           -0.975433  
3                 -0.994447           -0.987110  
4                 -0.996292           -0.982446  
...                     ...                 ...  
7347              -0.277608           -0.334216  
7348              -0.352629           -0.429959  
7349              -0.395901           -0.434122  
7350              -0.470140           -0.562069  
7351              -0.356768           -0.347220  

[7352 rows x 8 columns]

In [154]:
features_meanx = features[columns_meanx]


# build the model
binarytarget = pd.DataFrame(binarytarget)
log_reg = sm.Logit(binarytarget, features_meanx).fit()

         Current function value: inf
         Iterations: 35


/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1819: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/niclapenna/opt/anaconda3/envs/lhl_env/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1872: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


LinAlgError: Singular matrix

### Task 5
Now, let's fit Multinomial Logistic regression to predict all categories. Firstly, we can start with **Univariate** model for these features number separately:
+ 4
+ 54
- 19

Check the contingency matrix to see the effect of particular features!! (each feature can be good in predicting different categories)

### Task 6

Fit the Multinomial Logistic Regression model again. Now, try to choose **all** the important features we have in the dataset. Compare with your peers on who will get the best predictions with the smallest number of features?

### Task 7 (Stretch)
Create your own function for Stepwise selection. Use either sklearn or statsmodel.